Add details to the new project session
magrathealabs/playbook pull request #13
Opened 2018-05-05 17:50 UTC by alfakini

2018-05-05 18:50 UTC, izn requested changes

2018-05-06 14:14 UTC, danielSbastos approved these changes
(Take into consideration @izn comments)

2018-05-06 23:19 UTC, millnitzluan approved these changes

2018-05-07 13:31 UTC, diogotrentini requested changes

2018-05-07 17:38 UTC, izn approved these changes

2018-05-07 17:52 UTC, laurogripa approved these changes

2018-05-07 20:25 UTC, diogotrentini approved these changes

2018-05-07 23:31 UTC, merged