Add checklists section
magrathealabs/playbook pull request #15
Opened 2018-05-06 18:55 UTC by danielSbastos

Hi,
Here a new page. `3.3. Checklists` is added. It solely serves as a guideline for our projects, there is no need to follow it 100% given the fact that each project is unique. 

I did not write them, but rather copied from the referenced websites and removed duplicated sections that did seem important. Feel free to access the original content, compare the changes and suggest additions and/or removals.

2018-05-07 12:47 UTC, schweigert approved these changes

2018-05-07 18:03 UTC, laurogripa approved these changes

2018-05-07 23:44 UTC, alfakini requested changes
Some comments :)

2018-05-11 16:47 UTC, schweigert approved these changes

2018-05-14 18:42 UTC, alfakini approved these changes

2018-05-15 11:54 UTC, merged