Translate `3-engineering.md` to pt-BR
magrathealabs/playbook pull request #41
Opened 2019-03-15 14:48 UTC by gplichoski

Hi everyone!

As in the title, we translated `3-engineering.md` to pt-BR.

Closes #30

2019-03-26 17:10 UTC, izn requested changes
Ainda não terminei de revisar tudo, mas deixei alguns pontos que poderíamos melhorar.

O que vocês acham?

2019-03-27 16:00 UTC, laurogripa requested changes

2019-04-30 15:34 UTC, cuzik approved these changes
:cow:

2019-04-30 16:28 UTC, izn approved these changes

2019-05-02 13:07 UTC, merged