Translate `2-projects.md` to pt-BR
magrathealabs/playbook pull request #48
Opened 2019-04-26 15:11 UTC by schweigert

Hi MLabs team,

Este PR traduz de forma grosseira a documentação `2-projects.md` para Português.
Caso tenha mudanças para sugerir, utilize ` ```suggestion` do Github.

Closes #28

2019-04-30 17:38 UTC, bugarela reviewed
Revisei até Estimativas. A noite termino o documento.

2019-05-02 11:04 UTC, bugarela submitted a review, later dismissed

2019-05-02 13:41 UTC, pedroCervi requested changes
Some small suggestions

2019-05-02 13:46 UTC, pedroCervi approved these changes

2019-05-02 13:47 UTC, merged