Translate to `2.1-new-projects.md` to pt-BR
magrathealabs/playbook pull request #54
Opened 2019-04-29 11:54 UTC by danielSbastos

Closes #29

2019-04-29 13:32 UTC, gplichoski requested changes
Great work! :1st_place_medal: 
Left some suggestions only :smile:

2019-04-30 19:38 UTC, gplichoski approved these changes

2019-05-02 13:20 UTC, schweigert approved these changes

2019-05-02 13:21 UTC, schweigert approved these changes

2019-05-02 13:22 UTC, merged