Translate `1-organization.md` to pt-BR
magrathealabs/playbook pull request #55
Opened 2019-05-02 17:00 UTC by danielSbastos

Fixes https://github.com/magrathealabs/playbook/issues/24

2019-05-02 17:42 UTC, markx3 requested changes

2019-05-02 19:57 UTC, markx3 submitted a review, later dismissed
💯 

Just a small change. :)

2019-05-02 19:59 UTC, edrd-f submitted a review, later dismissed

2019-05-03 12:19 UTC, schweigert approved these changes

2019-05-03 12:19 UTC, merged