Review docs/organization/1-1-sharing.md
magrathealabs/playbook pull request #60
Opened 2019-05-09 17:48 UTC by alfakini

Hey people,

In this PR we improve the sharing docs. `docs/organization/1-1-sharing.md`

2019-05-10 12:33 UTC, schweigert approved these changes

2019-05-10 13:56 UTC, markx3 requested changes

2019-05-10 13:56 UTC, markx3 commented on docs/organization/1-1-sharing.md
> +Compartilhar conhecimento é muito importante para nós. Aprendemos muito com outras pessoas participando de conferências, lendo livros, blogs e códigos no GitHub. Usamos nosso tempo de investimento di
```suggestion
Compartilhar conhecimento é muito importante para nós. Aprendemos muito com outras pessoas participando de conferências, lendo livros, blogs e códigos no GitHub. Usamos nosso tempo de investimento disponível para fazer essas atividades acontecerem. Descrevemos aqui como contribuímos com a comunidade ao compartilhar nosso conhecimento.
```

2019-05-10 16:29 UTC, cuzik approved these changes

2019-05-10 16:30 UTC, markx3 approved these changes

2019-05-10 16:33 UTC, gplichoski reviewed
Bom trabalho :clap:

2019-05-10 16:33 UTC, gplichoski commented on docs/organization/1-1-sharing.md
> +Compartilhar conhecimento é muito importante para nós. Aprendemos muito com outras pessoas participando de conferências, lendo livros, blogs e códigos no GitHub. Usamos nosso tempo de investimento di
```suggestion
Compartilhar conhecimento é muito importante para nós. Aprendemos muito com outras pessoas participando de conferências, lendo livros, blogs e códigos no GitHub. Usamos nosso tempo de investimento disponível para fazer essas atividades. Descrevemos aqui como contribuímos com a comunidade ao compartilhar nosso conhecimento.
```

2019-05-10 16:33 UTC, gplichoski commented on docs/organization/1-1-sharing.md
> +Escrevemos _blogposts_ porque queremos compartilhar o que estamos fazendo e aprendendo sobre tecnologia, negócios e inovação. Quando estamos contratando, queremos que potenciais novas pessoas do time
`... e acompanhar na comunicação sobre o trabalho que fazemos ...` achei confuso, sinceramente não entendi o que isto quer dizer.

2019-05-10 16:33 UTC, gplichoski commented on docs/organization/1-1-sharing.md
> +Coletamos ideias para _blogposts_ em um [quadro do Trello](https://trello.com/b/ZrBmPW5n/mlabs-hacking), onde as discutimos antes de escrever. Frequentemente pegamos ideias desse quadro em nosso temp
```suggestion
Coletamos ideias para _blogposts_ em um [quadro do Trello](https://trello.com/b/ZrBmPW5n/mlabs-hacking), onde as discutimos antes de escrever. Frequentemente, pegamos ideias desse quadro em nosso tempo de investimento.
```
Sinceramente, não tenho certeza se vai esta vígula após frequentemente.

```
De um modo geral, não gostamos de pessoas estranhas.

“De um modo geral” é sinónimo de “geralmente”, adjunto adverbial de modo, por isso tem vírgula.

```
https://www.vortexmag.net/aprenda-a-usar-a-virgula-com-4-regras-simples/

2019-05-10 16:33 UTC, gplichoski commented on docs/organization/1-1-sharing.md
> +_Open Source_ é parte de nossa filosofia. Desde nossa concepção, temos sido uma empresa focada em _open source_, melhorando código compartilhado por outros, colocando esforço em escrita de código e d
```suggestion
_Open Source_ é parte da nossa filosofia. Desde nossa concepção, temos sido uma empresa focada em _open source_, melhorando código compartilhado por outros, colocando esforço em escrita de código e de forma geral dando suporte ao movimento _open source_. Construímos nossos produtos usando quase exclusivamente ferramentas _open source_.
```

Em uma pesquisa rasa, percebi que usa-se `de` em uma redação impessoal e na fala é mais comum o `da`. Como acredito que o _playbook_ é algo mais informal sugeri esta modificação. O que vocês acham?

2019-05-10 18:59 UTC, alfakini commented on docs/organization/1-1-sharing.md
> +Escrevemos _blogposts_ porque queremos compartilhar o que estamos fazendo e aprendendo sobre tecnologia, negócios e inovação. Quando estamos contratando, queremos que potenciais novas pessoas do time
Boa por tirar o "colaboradores", odeio essa palavra :)

2019-05-10 19:01 UTC, alfakini commented on docs/organization/1-1-sharing.md
> +_Open Source_ é parte de nossa filosofia. Desde nossa concepção, temos sido uma empresa focada em _open source_, melhorando código compartilhado por outros, colocando esforço em escrita de código e d
ÓtimO!

2019-05-14 14:19 UTC, diogotrentini requested changes

2019-05-14 14:19 UTC, diogotrentini commented on docs/organization/1-1-sharing.md
> +A coisa mais importante para se lembrar é que você deixará sua melhor impressão - pessoal e da empresa - se sua palestra for interessante, útil e bem apresentada. Palestras que funcionam bem tomam te
```suggestion
A coisa mais importante para se lembrar é que você deixará sua melhor impressão - pessoal e da empresa - se sua palestra for interessante, útil e bem apresentada. Palestras que funcionam bem tomam tempo. Se você precisar de ajuda, conselhos ou tempo para se preparar, não tenha receio de pedir. Criar publicações após o evento também é uma boa forma de compartilhar sua experiência e aprendizados.
```

2019-05-14 14:19 UTC, diogotrentini commented on docs/organization/1-1-sharing.md
> +Se estamos contratando, podemos mencionar isso ao final da palestra. Fale para as pessoas quais papéis estamos procurando e que todos são bem-vindos a falar com você após a palestra para conversar em
Temos uma política em relação às horas investidas em eventos que promovam a Magrathea de algum modo — vide Rails Girls. 50% das horas são consideradas no ponto. Acho que está faltando essa informação aqui, não? O próximo parágrafo fala apenas sobre custos.

2019-05-14 15:02 UTC, diogotrentini approved these changes

2019-05-14 16:08 UTC, merged