Review docs/organization/1-2-communication.md
magrathealabs/playbook pull request #61
Opened 2019-05-10 15:08 UTC by alfakini

Hey people,

In this PR we improve the communication docs. docs/organization/1-2-communication.md

2019-05-10 15:10 UTC, schweigert approved these changes

2019-05-10 16:18 UTC, cuzik commented on docs/organization/1-2-communication.md
> +* Se você receber um convite para uma reunião, não aceite se você achar que sua participação não é necessaria. Se for recurar envie uma nota explicando o motivo;
```suggestion
* Se você receber um convite para uma reunião, não aceite se você achar que sua participação não é necessaria. Se for recusar envie uma nota explicando o motivo;
```

2019-05-14 14:54 UTC, diogotrentini requested changes

2019-05-14 14:54 UTC, diogotrentini commented on docs/organization/1-2-communication.md
> +Comunicação é um dos nossos principais valores. Nós acreditamos que transparência e comunicação são essenciais para o bom desenvolvimento de produtos de Software. Com base em nossa experiência, enten
Temos duas frases repetindo "desenvolvimento [de produtos] de software", tornando a expressão repetitiva. O que acha do seguinte?

```suggestion
Comunicação é um dos nossos principais valores. Com base em nossa experiência, entendemos que a falta de comunicação é o principal gerador de problemas em projetos de desenvolvimento de software e, por isso, acreditamos que transparência e comunicação são essenciais na realização de tais projetos. Dependendo do projeto, do cliente e do time, definimos diferentes pontos e rotinas de comunicação.
```

2019-05-14 14:54 UTC, diogotrentini commented on docs/organization/1-2-communication.md
> +* O que pode ser melhorado.
Acho que podemos adicionar:

```suggestion
* O que pode ser melhorado;
* Apresentação de novos mochileiros.
```

2019-05-14 14:54 UTC, diogotrentini commented on docs/organization/1-2-communication.md
> +* Fluxo de caixa: um resumo dos principais fundos e débitos de entrada e saída.
Acho que podemos usar "receitas, custos e despesas" ao invés de "entrada e saída". Além disso, acho que podemos usar "DRE" ao invés de "Fluxo de caixa" (porque falamos de mais coisas além do fluxo de caixa).

```suggestion
* DRE: um resumo da nossa contabilidade no exercício, detalhando receitas, custos e despesas da empresa.
```

2019-05-14 14:54 UTC, diogotrentini commented on docs/organization/1-2-communication.md
> +* Fluxo de caixa: um resumo dos principais fundos e débitos de entrada e saída.
Mesmo comentário sobre o DRE.

2019-05-14 14:54 UTC, diogotrentini commented on docs/projects/2-projects.md
> +Revise as tarefas de engenharia e refatoração. Puxe os cartões para o Backlog com base no que o cliente, os designers e os desenvolvedores acreditam ser apropriado, considerando o design do produto e
Eu removeria esse parágrafo e deixaria apenas o próximo. Não acho que "queremos estar sempre consertando o que está quebrado primeiro". Por mais que temos uma ânsia em arrumar as coisas, isso só faz sentido se alinharmos isso ao plano, considerando a prioridade de outras tarefas do projeto. Todo bug consertado tem um impacto econômico e, por isso, ele deve ser priorizado juntamente com as demais tarefas.

```suggestion
Revise as tarefas de novas funcionalidades, correções de bug e refatoração. Puxe os cartões para o Backlog com base no que o cliente, os designers e os desenvolvedores acreditam ser apropriado, considerando o custo e retorno de cada tarefa. Reordene toda a fila do Backlog de acordo com a prioridade. Os cartões que estavam no topo da lista na semana passada podem ser movidos para o fundo ou para outros quadros ou listas.
```

2019-05-14 14:54 UTC, diogotrentini commented on docs/projects/2-projects.md
> +O sistema de gerenciamento de tarefas é o repositório canônico para planos. Quando as coisas só são ditas ao telefone, pessoalmente, em e-mails que não incluem todo o grupo ou em bate-papos particula
Entendi a primeira frase, mas acho que pode ser um pouco confusa. Eu tentaria deixar a linguagem mais fácil de ser compreendida. Algo como:

```suggestion
O sistema de gerenciamento de tarefas (normalmente o Trello) é o principal lugar onde guardamos informações sobre o plano do projeto. Quando as coisas só são ditas ao telefone, pessoalmente, em e-mails que não incluem todo o grupo ou em bate-papos particulares, as informações são perdidas, esquecidas ou mal interpretadas. Os problemas se expandem quando alguém entra ou sai do projeto.
```

2019-05-14 14:55 UTC, diogotrentini commented on docs/projects/2-projects.md
> +    Esta seção está sem conteúdo sobre Kanban e fluxo contínuo
Essas informações iriam aqui, na seção da reunião de planejamento?

2019-05-14 16:44 UTC, alfakini commented on docs/projects/2-projects.md
> +    Esta seção está sem conteúdo sobre Kanban e fluxo contínuo
Retirei, era só um aviso.

2019-05-14 16:48 UTC, diogotrentini approved these changes

2019-05-14 17:17 UTC, merged